# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: '42 * * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn
      - run: yarn apicheck
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
          add: 'README.md'
          author_name: narze's bot
          author_email: notbarze@users.noreply.github.com
          message: 'Update README.md'
          push: true
